### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by martin3000** [zigpy/zigpy-deconz#50]
I have a conbee 2 stick and would like to test if the stick works with zigpy. 
In home assistant, I get "Frame received" messages when pairing, but no pairing is possible. No device is added. I have no glue how to debug this.

HA 0.94.4

**Comment by Adminiuga** [comment]
Enable debug logging
`logger.set_level` service call to temporarily bump levels
```
{
    "asyncio": "debug"
    "homeassistant.components.zha": "debug"
    "zigpy": "debug"
    "bellows": "debug"
    "zigpy_xbee": "debug"
    "zigpy_deconz": "debug"
}
```

`logger:` `configuration.yaml` to set level permanently
```
logger:
  default: info
  logs:
    asyncio: debug
    homeassistant.components.zha: debug
    zigpy: debug
    bellows: debug
    zigpy_xbee: debug
    zigpy_deconz: debug
```


Call 'zha.permit' service from services dev panel. Or from config panel -> zha -> add devices
