### ISSUE TITLE
Question; Ikea remote 5 button switch (how to create automation)

### ISSUE THREAD

**Issue by pergolafabio** [zigpy/zigpy-deconz#67]
This is a question, did anyone succeed to create an automation for the ikea remote switch (5 button version) , every button has different arguments, but seems below code doesnt work, it always run regardless the button is pressed

thnx in advance
```
- id: '1562807168430'
  alias: Basement Remote - right arrow press
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: '00:0d:6f:ff:fe:62:50:cf'
      command: 'press'
      args:
        - 0
        - 1
        - 13
        - 0
  condition: []
  action:
  - service: light.toggle
    data:
      entity_id: 
        - light.basement_couch_lights_level
```
